In [1]:
import numpy as np
import pandas as pd
base_path = "C:/Users/99818854/Projetos/GitRep/adaptive_learning"

In [2]:
df = pd.read_csv(f"{base_path}/data/Dataset_model.csv", low_memory=False)

In [4]:
df["acertou"].unique()

array([0, 1], dtype=int64)

In [23]:
data = []
for user in df["novo_user_id"].unique():
    subset = df.query(f"novo_user_id == {user}").sort_values("created_at")
    areas = {}

    for i in range(0, len(subset)):
        area = subset["knowledge_area_id"].values[i]
        if area not in areas.keys():
            areas[area] = {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0}

        if subset["acertou"].values[i] == 1:
            areas[area][0] = areas[area][0] + 1
            difficulty = subset["difficulty"].values[i]

            if not difficulty:
                areas[area][difficulty] = areas[area][difficulty] + 1

        data.append({
            "user_id": subset["novo_user_id"].values[i],
            "area": subset["knowledge_area_id"].values[i],
            "difficulty": difficulty,
            "points": areas[area][0],
            "points1": areas[area][1],
            "points2": areas[area][2],
            "points3": areas[area][3],
            "points4": areas[area][4],
            "points5": areas[area][5],
            "right": subset["acertou"].values[i]
        })

data = pd.DataFrame(data)
data.to_csv(f"{base_path}/data/mastery.csv", index=False)

In [21]:
np.dot(data.values[:, 2:-1], [[1], [0.5], [0.5], [0.5], [0.7], [0.8]])

array([[ 0. ],
       [ 0. ],
       [ 1.5],
       ...,
       [78.6],
       [78.6],
       [78.6]])

In [18]:
data.values[:, 2:-1][0]

array([0., 0., 0., 0., 0., 0.])

In [17]:
data

user_id  area  points  points1  points2  points3  points4  points5  \
0              1  13.0       0        0        0        0        0        0   
1              1  13.0       0        0        0        0        0        0   
2              1  13.0       1        0        0        1        0        0   
3              1  13.0       1        0        0        1        0        0   
4              1  13.0       2        0        0        2        0        0   
...          ...   ...     ...      ...      ...      ...      ...      ...   
1999995    20000  27.0      51       15       22       11        3        0   
1999996    20000  27.0      52       16       22       11        3        0   
1999997    20000  27.0      52       16       22       11        3        0   
1999998    20000  27.0      52       16       22       11        3        0   
1999999    20000  27.0      52       16       22       11        3        0   

         right  
0            0  
1            0  
2            1  
3            0  
4            1  
...        ...  
1999995      1  
1999996      1  
1999997      0  
1999998      0  
1999999      0  

[2000000 rows x 9 columns]

In [4]:
data = []
mean_difficulty = round(np.mean(df["difficulty"].dropna()))
#mean_difficulty = 0
for user in df["novo_user_id"].unique():
    subset = df.query(f"novo_user_id == {user}").sort_values("created_at")
    for i in range(0, len(subset)):
        data.append({
            "user_id": subset["novo_user_id"].values[i],
            "difficulty": mean_difficulty if np.isnan(subset["difficulty"].values[i]) else subset["difficulty"].values[i],
            "area": subset["knowledge_area_id"].values[i],
            "right": subset["acertou"].values[i]
        })

data = pd.DataFrame(data)
data.to_csv(f"{base_path}/data/mastery.csv", index=False)